apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: scale
  namespace: demo
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          containerConcurrency: 1
          container:
            image: gcr.io/knative-samples/rester-tester:latest
            resources:
              requests:
                memory: "128Mi"
                cpu: "0.5"
              limits:
                memory: "256Mi"
                cpu: "1"
            env:
            - name: T_VERSION
              value: "1.1.2"
