apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: simple
  namespace: demo
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/knative-samples/rester-tester:latest
            env:
            - name: SIMPLE_MSG
              value: "Hello World"
