apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: bg2
  namespace: next
spec:
  revisionTemplate:
    spec:
      container:
        image: gcr.io/knative-samples/knative-route-demo:green # The URL to the sample image
        env:
          - name: T_VERSION
            value: "green"
---
apiVersion: serving.knative.dev/v1alpha1
kind: Route
metadata:
  name: bg # Route name is unchanged, since we're updating an existing Route
  namespace: next
spec:
  traffic:
  # kubectl get revisions -n next | grep bg-
  - configurationName: bg1
    percent: 100 # All traffic still going to the first revision
  - configurationName: bg2
    percent: 0 # 0% of traffic routed to the second revision
    name: v2 # A named route