apiVersion: serving.knative.dev/v1alpha1
kind: Route
metadata:
  name: bg # Route name is unchanged, since we're updating an existing Route
  namespace: next
spec:
  traffic:
  - configurationName: bg1
    percent: 0 # All traffic still going to the first revision
    name: v1 # A named route
  - configurationName: bg2
    percent: 100 # 0% of traffic routed to the second revision