apiVersion: serving.knative.dev/v1alpha1
kind: Route
metadata:
  name: bg # Route name is unchanged, since we're updating an existing Route
  namespace: next
spec:
  traffic:
  - configurationName: bg1
    percent: 50 # All traffic still going to the first revision
  - configurationName: bg2
    percent: 50 # 0% of traffic routed to the second revision
    name: v2 # A named route