apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: kcm-scored-trigger
spec:
  filter:
    sourceAndType:
      type: com.twitter.scored
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: scored-eventstore